version: '3.7'

services:
  sagaorchestrationdemo.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - SAGA_CONN:Host=sagaorchestrationdemo.database;Port=5432;Database=SagaDemo;User Id=postgres;Password=postgres;
    ports:
      - 8081:80
    networks:
      - sagaorchestrationdemo-network
    depends_on:
      - sagaorchestrationdemo.database

  sagaorchestrationdemo.database:
    image: postgres:9.5
    restart: always
    environment:  
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - sagaorchestrationdemo-network

volumes:  
  pgdata: 

networks:
  sagaorchestrationdemo-network: